var app_root = 'src/main/webapp/client/';
module.exports = {
    app: app_root,
    dist: 'dist/',
    scss: app_root + 'scss/',
    sassSrc: app_root + 'scss/**/*.{scss,sass}',
    cssDir: app_root + 'assets/css',
    fontsDir: app_root + 'assets/fonts',
    staticCssDir: app_root + 'assets/staticCss',
    jsDir: app_root + 'assets/js',
    menuDir: app_root + 'menu/',
    bower: app_root + 'bower_components/',
    tmp: app_root + 'tmp',
    revManifest: app_root + 'tmp/rev-manifest.json',
    port: 9000,
    apiPort: 8080,
    liveReloadPort: 35729,
    uri: 'http://localhost:',
    constantTemplate: '(function () {\n' +
    '    \'use strict\';\n' +
    '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
    '    angular\n' +
    '        .module(\'<%- moduleName %>\')\n' +
    '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n' +
    '})();\n'
};
